version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_dumps:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: graphql
      MYSQL_DATABASE: graphql
      MYSQL_ENTRYPOINT_INITDB: ./mysql/docker-entrypoint-initdb.d    
    healthcheck:
      test: "/usr/bin/mysql graphql --user=root --password=graphql --execute \"SHOW TABLES;\""
      interval: 2s
      timeout: 20s
      retries: 10
